"""initial migration with users jumps and marks

Revision ID: 807155f6e686
Revises: 
Create Date: 2025-11-07 19:16:35.244083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807155f6e686'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='ID único do usuário'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email único'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Hash da senha (ou OAuth)'),
    sa.Column('role', sa.String(length=50), nullable=False, comment="Papel: 'atleta' ou 'treinador'"),
    sa.Column('google_id', sa.String(length=255), nullable=True, comment='ID Google OAuth'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Ativo/Inativo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Criação'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Última atualização'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Último login'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_google_id', 'users', ['google_id'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('athlete_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='ID do usuário (único)'),
    sa.Column('coach_id', sa.UUID(as_uuid=False), nullable=True, comment='ID do treinador responsável'),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('altura_cm', sa.Integer(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('tamanho_pe', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('prova_principal', sa.String(length=100), nullable=True),
    sa.Column('prova_secundaria', sa.String(length=100), nullable=True),
    sa.Column('tempo_experiencia', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('tipo_sanguineo', sa.String(length=5), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('medicamentos', sa.Text(), nullable=True),
    sa.Column('contato_emergencia', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('altura_cm IS NULL OR (altura_cm >= 100 AND altura_cm <= 250)', name='check_altura'),
    sa.CheckConstraint('peso_kg IS NULL OR (peso_kg >= 30 AND peso_kg <= 200)', name='check_peso'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_athlete_coach_id', 'athlete_profiles', ['coach_id'], unique=False)
    op.create_index('idx_athlete_user_id', 'athlete_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_athlete_profiles_user_id'), 'athlete_profiles', ['user_id'], unique=True)
    op.create_table('coach_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='ID do usuário (único)'),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('especialidade', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('certificacoes', sa.Text(), nullable=True),
    sa.Column('anos_experiencia', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coach_user_id', 'coach_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_coach_profiles_user_id'), 'coach_profiles', ['user_id'], unique=True)
    op.create_table('jumps',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='ID único do registro'),
    sa.Column('athlete_id', sa.UUID(as_uuid=False), nullable=False, comment='ID do atleta'),
    sa.Column('date', sa.Date(), nullable=False, comment='Data do treino'),
    sa.Column('jump1', sa.Float(), nullable=False, comment='Primeiro salto (cm)'),
    sa.Column('jump2', sa.Float(), nullable=False, comment='Segundo salto (cm)'),
    sa.Column('jump3', sa.Float(), nullable=False, comment='Terceiro salto (cm)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Observações do treino'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('jump1 <= 200', name='check_jump1_max'),
    sa.CheckConstraint('jump1 > 0', name='check_jump1_positive'),
    sa.CheckConstraint('jump2 <= 200', name='check_jump2_max'),
    sa.CheckConstraint('jump2 > 0', name='check_jump2_positive'),
    sa.CheckConstraint('jump3 <= 200', name='check_jump3_max'),
    sa.CheckConstraint('jump3 > 0', name='check_jump3_positive'),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'date', name='unique_athlete_date')
    )
    op.create_index('idx_jumps_athlete_date', 'jumps', ['athlete_id', 'date'], unique=False)
    op.create_index(op.f('ix_jumps_athlete_id'), 'jumps', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_jumps_date'), 'jumps', ['date'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='ID único da marca'),
    sa.Column('athlete_id', sa.UUID(as_uuid=False), nullable=False, comment='ID do atleta'),
    sa.Column('evento', sa.String(length=100), nullable=False, comment='Evento (100m, 200m, 400m, etc.)'),
    sa.Column('resultado', sa.Float(), nullable=False, comment='Tempo em segundos'),
    sa.Column('vento', sa.Float(), nullable=True, comment='Vento em m/s'),
    sa.Column('data', sa.Date(), nullable=False, comment='Data da prova'),
    sa.Column('local', sa.String(length=255), nullable=True, comment='Local da prova'),
    sa.Column('tipo', sa.String(length=50), nullable=False, comment="Tipo: 'competicao' ou 'teste'"),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("tipo IN ('competicao','teste')", name='check_tipo_valid'),
    sa.CheckConstraint('resultado > 0', name='check_resultado_positive'),
    sa.CheckConstraint('vento IS NULL OR (vento >= -5 AND vento <= 5)', name='check_vento_range'),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_marks_athlete_date', 'marks', ['athlete_id', 'data'], unique=False)
    op.create_index('idx_marks_athlete_evento', 'marks', ['athlete_id', 'evento'], unique=False)
    op.create_index('idx_marks_evento', 'marks', ['evento'], unique=False)
    op.create_index('idx_marks_tipo', 'marks', ['tipo'], unique=False)
    op.create_index(op.f('ix_marks_athlete_id'), 'marks', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_marks_data'), 'marks', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marks_data'), table_name='marks')
    op.drop_index(op.f('ix_marks_athlete_id'), table_name='marks')
    op.drop_index('idx_marks_tipo', table_name='marks')
    op.drop_index('idx_marks_evento', table_name='marks')
    op.drop_index('idx_marks_athlete_evento', table_name='marks')
    op.drop_index('idx_marks_athlete_date', table_name='marks')
    op.drop_table('marks')
    op.drop_index(op.f('ix_jumps_date'), table_name='jumps')
    op.drop_index(op.f('ix_jumps_athlete_id'), table_name='jumps')
    op.drop_index('idx_jumps_athlete_date', table_name='jumps')
    op.drop_table('jumps')
    op.drop_index(op.f('ix_coach_profiles_user_id'), table_name='coach_profiles')
    op.drop_index('idx_coach_user_id', table_name='coach_profiles')
    op.drop_table('coach_profiles')
    op.drop_index(op.f('ix_athlete_profiles_user_id'), table_name='athlete_profiles')
    op.drop_index('idx_athlete_user_id', table_name='athlete_profiles')
    op.drop_index('idx_athlete_coach_id', table_name='athlete_profiles')
    op.drop_table('athlete_profiles')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_google_id', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
